version: '3.0'

services:
  database:
    container_name: database
    hostname: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin